[package]
name = "rivetdb-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rivetdb = { path = ".." }
tokio = { version = "1.39", features = ["rt-multi-thread", "macros"] }
